import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.infoContainer}>
                    <Image
                        src="https://sourav-main-portfolio.netlify.app/static/media/my-portfolio-img-1.99c7a05eb560f6c30354.jpg"
                        width={2048}
                        height={1536}
                        alt=""
                    />

                    <div className={styles.content}>
                        <h1>HI</h1>
                    </div>
                </div>
            </main>
        </>
    );
}
